name: Get counter from an API
description: This adapter sends an unique number
node_identifier: counter
platforms:
  - Docker
data_sources:
  - name: counter
    url: https://adapter.blockchain-tracability.fr
parameters:
  - token
